export enum IconType {
  dragIndicator = 'dragIndicator',
  motionCanvas = 'motionCanvas',
  pause = 'pause',
  photoCamera = 'photoCamera',
  play = 'play',
  repeat = 'repeat',
  skipNext = 'skipNext',
  skipPrevious = 'skipPrevious',
  tune = 'tune',
  videoSettings = 'videoSettings',
  volumeOn = 'volumeOn',
  volumeOff = 'volumeOff',
  schedule = 'schedule',
  warning = 'warning',
  bug = 'bug',
  clear = 'clear',
  locate = 'locate',
}
