import { KeyCode } from "../global"
export default KeyCodes = {
   SPACEBAR = new KeyCode(' ', 'Space'),
   ESCAPE = new KeyCode('Escape', 'ESC'),
   SHIFT = new KeyCode('Shift', 'Shift'),

   UP_ARROW = new KeyCode('ArrowUp', '↑', 'Up Arrow'),
   DOWN_ARROW = new KeyCode('ArrowDown', '↓', 'Down Arrow'),
   RIGHT_ARROW = new KeyCode('ArrowRight', '->', 'Right Arrow'),
   LEFT_ARROW = new KeyCode('ArrowLeft', '<-', 'Left Arrow'),

   QUOTE = new KeyCode("'", 'Quote'),

   KEY_EQUALS = new KeyCode('=', '=', 'Equals'),
   KEY_PLUS = new KeyCode('+', '+', 'Plus'),
   KEY_MINUS = new KeyCode('-', '-', 'Minus'),

   KEY_0 = new KeyCode('0', '0'),
   KEY_1 = new KeyCode('1', '1'),
   KEY_2 = new KeyCode('2', '2'),
   KEY_3 = new KeyCode('3', '3'),
   KEY_4 = new KeyCode('4', '4'),
   KEY_5 = new KeyCode('5', '5'),
   KEY_6 = new KeyCode('6', '6'),
   KEY_7 = new KeyCode('7', '7'),
   KEY_8 = new KeyCode('8', '8'),
   KEY_9 = new KeyCode('9', '9'),

   KEY_A = new KeyCode('a', 'A'),
   KEY_B = new KeyCode('b', 'B'),
   KEY_C = new KeyCode('c', 'C'),
   KEY_D = new KeyCode('d', 'D'),
   KEY_E = new KeyCode('e', 'E'),
   KEY_F = new KeyCode('f', 'F'),
   KEY_G = new KeyCode('g', 'G'),
   KEY_H = new KeyCode('h', 'H'),
   KEY_I = new KeyCode('i', 'I'),
   KEY_J = new KeyCode('j', 'J'),
   KEY_K = new KeyCode('k', 'K'),
   KEY_L = new KeyCode('l', 'L'),
   KEY_M = new KeyCode('m', 'M'),
   KEY_N = new KeyCode('n', 'N'),
   KEY_O = new KeyCode('o', 'O'),
   KEY_P = new KeyCode('p', 'P'),
   KEY_Q = new KeyCode('q', 'Q'),
   KEY_R = new KeyCode('r', 'R'),
   KEY_S = new KeyCode('s', 'S'),
   KEY_T = new KeyCode('t', 'T'),
   KEY_U = new KeyCode('u', 'U'),
   KEY_V = new KeyCode('v', 'V'),
   KEY_W = new KeyCode('w', 'W'),
   KEY_X = new KeyCode('x', 'X'),
   KEY_Y = new KeyCode('y', 'Y'),
   KEY_Z = new KeyCode('z', 'Z'),
}
