name: Deploy Documentation to GitHub Pages

on: workflow_dispatch

env:
  HUSKY: 0

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npx lerna run build
      - run: npx lerna run bundle
      - run: npm run examples:build
      - run: npm run ui:showcase
      - run: npm run docs:build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./packages/docs/build
          external_repository: motion-canvas/motion-canvas.github.io
